---
# Instala las herramientas de base el server

- name: Instalar dependencias para el apt y fixear el update 
  shell: | 
     /usr/bin/apt clean && /usr/bin/apt update
     apt-get -y install python3.6
     apt-get -y --reinstall install python3-apt
     ln -sf /usr/bin/python3.6 /usr/bin/python
  args:
    executable: /bin/sh

- name: Instalar repos adicionales para Ubuntu 18
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu bionic universe
    state: present

- name: Create symbolic link de python -> python3.7
  file:
    src: /usr/bin/python3.6
    dest: /usr/bin/python
    owner: root
    group: root
    state: link 

- name: Instalar dependencias para el server
  apt: 
    pkg: 
      - nginx
      - certbot
      - python3-mysqldb
      - python3-pymysql
      - rrdtool
      - htop
      - whois
      - mtr-tiny
      - vim-tiny
      - wget
      - curl
      - snmp
      - snmpd
      - software-properties-common
    update_cache: yes

- name: Create symbolic link de python -> python3.6
  file:
    src: /usr/bin/python3.6
    dest: /usr/bin/python
    owner: root
    group: root
    state: link 

- name: Copia config. de SNMP
  template: 
    src=snmpd.conf.j2 
    dest=/etc/snmp/snmpd.conf

- name: Copia /etc/aliases
  copy:
    src: files/aliases
    dest: /etc
    owner: root
    group: root
    mode: 0644

# - name: Deshabilito UFW
#  ufw:
#    state: disabled