FROM ubuntu:focal
RUN apt-get clean && apt-get update 
RUN apt-get -y install --reinstall python3-apt apt-utils
RUN apt-get -y install bind9 bind9-dnsutils bind9-host vim-tiny rsync figlet iputils-ping net-tools
