---
# This playbook deploys the tutorial environment
#
# (c) CarlosM, based on previous example by juancarlos@lacnic.net
# v1 20210508

- name: Instala utiles y paquetes basicos
  hosts: all
  remote_user: root
  become: true

  roles:
    - users_and_packages
    - configure_environment
