# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # config.vm.box = "ubuntu/bionic64"
  # config.vm.box = "ubuntu/xenial64"
  config.vm.box = "ubuntu/focal64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 3000, host: 3000, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 53, host: 5300, host_ip: "127.0.0.1"

  # config.vm.provision "ansible" do |ansible|
  #   ansible.playbook = "site.yml"
  #   ansible.become = true
  #   ansible.become_user = "root"
  # end
  config.vm.provision "shell", inline: <<-SHELL
    echo "Preconfig #1" 
    echo " "
    apt-get update 
    apt-get -y install ansible net-tools figlet
    cd /vagrant
    ansible-playbook -i hosts_tutorial.txt site.yml
    cd /vagrant
    docker-compose up -d
    usermod -a -G docker vagrant
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    echo "MAQUINA LISTA!" | figlet -w 120
    echo " "
    docker ps
  SHELL

end
